// List notes variables
export const POSTS_LIST_REQUEST = "POSTS_LIST_REQUEST";
export const POSTS_LIST_SUCCESS = "POSTS_LIST_SUCCESS";
export const POSTS_LIST_FAILURE = "POSTS_LIST_FAILURE";

// Create note variables
export const POSTS_CREATE_REQUEST = "POSTS_CREATE_REQUEST";
export const POSTS_CREATE_SUCCESS = "POSTS_CREATE_SUCCESS";
export const POSTS_CREATE_FAILURE = "POSTS_CREATE_FAILURE";
