// List post variables
export const POSTS_LIST_REQUEST = "POSTS_LIST_REQUEST";
export const POSTS_LIST_SUCCESS = "POSTS_LIST_SUCCESS";
export const POSTS_LIST_FAILURE = "POSTS_LIST_FAILURE";

// Create post variables
export const POSTS_CREATE_REQUEST = "POSTS_CREATE_REQUEST";
export const POSTS_CREATE_SUCCESS = "POSTS_CREATE_SUCCESS";
export const POSTS_CREATE_FAILURE = "POSTS_CREATE_FAILURE";

// Edit posts variables
export const POSTS_UPDATE_REQUEST = "POSTS_UPDATE_REQUEST";
export const POSTS_UPDATE_SUCCESS = "POSTS_UPDATE_SUCCESS";
export const POSTS_UPDATE_FAILURE = "POSTS_UPDATE_FAILURE";

// Delete posts variables
export const POSTS_DELETE_REQUEST = "POSTS_DELETE_REQUEST";
export const POSTS_DELETE_SUCCESS = "POSTS_DELETE_SUCCESS";
export const POSTS_DELETE_FAILURE = "POSTS_DELETE_FAILURE";
